-- Seed clasico para practicar PostgreSQL con datos reales de ejemplo.

BEGIN;

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS employee_projects CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

CREATE TABLE departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  location text NOT NULL
);

CREATE TABLE employees (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer REFERENCES departments(id),
  manager_id integer REFERENCES employees(id),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  hire_date date NOT NULL,
  job_title text NOT NULL,
  salary numeric(10,2) NOT NULL CHECK (salary > 0),
  status text NOT NULL DEFAULT 'active'
);

CREATE TABLE projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer REFERENCES departments(id),
  name text NOT NULL UNIQUE,
  budget numeric(12,2) NOT NULL CHECK (budget >= 0),
  start_date date NOT NULL,
  end_date date
);

CREATE TABLE employee_projects (
  employee_id integer NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  assigned_at date NOT NULL DEFAULT CURRENT_DATE,
  role text NOT NULL,
  PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  city text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers(id),
  order_date date NOT NULL,
  status text NOT NULL,
  total_amount numeric(12,2) NOT NULL CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0)
);

INSERT INTO departments (name, location) VALUES
  ('Engineering', 'Lima'),
  ('Sales', 'Bogota'),
  ('HR', 'Mexico City'),
  ('Finance', 'Buenos Aires');

INSERT INTO employees (department_id, manager_id, first_name, last_name, email, hire_date, job_title, salary, status) VALUES
  (1, NULL, 'Ana', 'Torres', 'ana.torres@acme.test', '2022-01-10', 'Engineering Manager', 5200.00, 'active'),
  (1, 1, 'Luis', 'Garcia', 'luis.garcia@acme.test', '2022-03-15', 'Backend Engineer', 4100.00, 'active'),
  (1, 1, 'Marta', 'Perez', 'marta.perez@acme.test', '2023-07-01', 'Data Engineer', 4300.00, 'active'),
  (2, NULL, 'Sofia', 'Ramos', 'sofia.ramos@acme.test', '2021-11-20', 'Sales Lead', 4900.00, 'active'),
  (2, 4, 'Diego', 'Mendoza', 'diego.mendoza@acme.test', '2024-02-05', 'Account Executive', 3600.00, 'active'),
  (3, NULL, 'Paula', 'Castro', 'paula.castro@acme.test', '2020-05-18', 'HR Specialist', 3400.00, 'active'),
  (4, NULL, 'Javier', 'Lopez', 'javier.lopez@acme.test', '2019-09-12', 'Finance Analyst', 4600.00, 'active');

INSERT INTO projects (department_id, name, budget, start_date, end_date) VALUES
  (1, 'Migration API', 25000.00, '2025-01-15', NULL),
  (1, 'Analytics Pipeline', 32000.00, '2025-03-01', NULL),
  (2, 'CRM Rollout', 18000.00, '2025-02-10', NULL),
  (4, 'Budget Forecast 2025', 12000.00, '2025-01-20', '2025-12-31');

INSERT INTO employee_projects (employee_id, project_id, assigned_at, role) VALUES
  (1, 1, '2025-01-15', 'Owner'),
  (2, 1, '2025-01-20', 'Developer'),
  (3, 2, '2025-03-02', 'Data Modeler'),
  (4, 3, '2025-02-11', 'Sponsor'),
  (5, 3, '2025-02-15', 'Sales Rep'),
  (7, 4, '2025-01-21', 'Analyst');

INSERT INTO customers (first_name, last_name, email, city, created_at) VALUES
  ('Camila', 'Suarez', 'camila.suarez@example.com', 'Lima', '2025-04-01 09:15:00+00'),
  ('Pedro', 'Vega', 'pedro.vega@example.com', 'Bogota', '2025-04-02 12:30:00+00'),
  ('Laura', 'Nunez', 'laura.nunez@example.com', 'Santiago', '2025-04-03 08:45:00+00'),
  ('Mario', 'Diaz', 'mario.diaz@example.com', 'Lima', '2025-04-04 17:20:00+00');

INSERT INTO orders (customer_id, order_date, status, total_amount) VALUES
  (1, '2025-04-05', 'paid', 149.90),
  (1, '2025-04-10', 'shipped', 89.50),
  (2, '2025-04-11', 'paid', 240.00),
  (3, '2025-04-12', 'cancelled', 65.00),
  (4, '2025-04-13', 'paid', 120.00);

INSERT INTO order_items (order_id, product_name, quantity, unit_price) VALUES
  (1, 'Keyboard', 1, 49.90),
  (1, 'Mouse', 2, 50.00),
  (2, 'USB-C Cable', 3, 29.83),
  (3, 'Monitor', 1, 240.00),
  (4, 'Notebook', 5, 13.00),
  (5, 'Desk Lamp', 2, 60.00);

COMMIT;
