/**
 * Tests for parseSeedSchema — validates that the parser correctly
 * extracts tables and columns, and excludes constraint-only lines.
 *
 * Uses a realistic SQL fixture that mirrors the structure of
 * seed/classic_company.sql (7 tables, real column types, composite PKs).
 */

import { describe, it, expect } from 'vitest';
import { parseSeedSchema } from '../parse-seed.ts';
// The real seed the rail renders from. Imported as a raw string (same `?raw`
// the lesson page uses) so the parser is guarded against the actual file
// drifting — not just a fixture that mirrors it today.
import realSeedSql from '../../../../seed/classic_company.sql?raw';

// Minimal fixture that mirrors the actual seed's CREATE TABLE structure.
const FIXTURE_SQL = `
CREATE TABLE departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  location text NOT NULL
);

CREATE TABLE employees (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer REFERENCES departments(id),
  manager_id integer REFERENCES employees(id),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  hire_date date NOT NULL,
  job_title text NOT NULL,
  salary numeric(10,2) NOT NULL CHECK (salary > 0),
  status text NOT NULL DEFAULT 'active'
);

CREATE TABLE projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id integer REFERENCES departments(id),
  name text NOT NULL UNIQUE,
  budget numeric(12,2) NOT NULL CHECK (budget >= 0),
  start_date date NOT NULL,
  end_date date
);

CREATE TABLE employee_projects (
  employee_id integer NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  assigned_at date NOT NULL DEFAULT CURRENT_DATE,
  role text NOT NULL,
  PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL UNIQUE,
  city text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers(id),
  order_date date NOT NULL,
  status text NOT NULL,
  total_amount numeric(12,2) NOT NULL CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0)
);
`;

describe('parseSeedSchema — tables', () => {
  it('returns exactly 7 tables in source order', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    expect(tables).toHaveLength(7);
    expect(tables.map((t) => t.table)).toEqual([
      'departments',
      'employees',
      'projects',
      'employee_projects',
      'customers',
      'orders',
      'order_items',
    ]);
  });
});

describe('parseSeedSchema — employees table', () => {
  it('has 10 columns', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    const employees = tables.find((t) => t.table === 'employees')!;
    expect(employees.columns).toHaveLength(10);
  });

  it('includes salary typed numeric(10,2)', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    const employees = tables.find((t) => t.table === 'employees')!;
    const salary = employees.columns.find((c) => c.name === 'salary');
    expect(salary).toBeDefined();
    expect(salary!.type).toBe('numeric(10,2)');
  });

  it('includes department_id typed integer', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    const employees = tables.find((t) => t.table === 'employees')!;
    const deptId = employees.columns.find((c) => c.name === 'department_id');
    expect(deptId).toBeDefined();
    expect(deptId!.type).toBe('integer');
  });
});

describe('parseSeedSchema — constraint exclusion', () => {
  it('does not include constraint-only lines as columns', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    for (const { columns } of tables) {
      for (const col of columns) {
        expect([
          'primary',
          'foreign',
          'unique',
          'check',
          'constraint',
        ]).not.toContain(col.name.toLowerCase());
      }
    }
  });

  it('employee_projects has 4 columns (composite PK line is excluded)', () => {
    const tables = parseSeedSchema(FIXTURE_SQL);
    const ep = tables.find((t) => t.table === 'employee_projects')!;
    expect(ep.columns).toHaveLength(4);
  });
});

describe('parseSeedSchema — against the real seed', () => {
  it('parses the 7 company tables in order from classic_company.sql', () => {
    const tables = parseSeedSchema(realSeedSql);
    expect(tables.map((t) => t.table)).toEqual([
      'departments',
      'employees',
      'projects',
      'employee_projects',
      'customers',
      'orders',
      'order_items',
    ]);
  });

  it('keeps the rail honest: employees has 10 columns incl. salary numeric(10,2)', () => {
    const tables = parseSeedSchema(realSeedSql);
    const employees = tables.find((t) => t.table === 'employees')!;
    expect(employees.columns).toHaveLength(10);
    expect(employees.columns.find((c) => c.name === 'salary')?.type).toBe(
      'numeric(10,2)',
    );
  });
});
